routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('index');

Auth::routes([
    'register' => false, // remove this class to activate register route
    'reset' => false, // remove this class to activate password reset ro+ute
    'confirm' => false, // remove this class to activate password confirmation route
    'verify' => false // remove this class to activate email verification route
]);
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
    Route::get('gambar/{id}', [App\Http\Controllers\KelasBusController::class, 'listGambar'])->name('bus.gambar');
    Route::resource('component', App\Http\Controllers\ComponentController::class)->except('destroy');
    Route::resource('bus', App\Http\Controllers\KelasBusController::class)->except('destroy');
    Route::delete('component/delete', [App\Http\Controllers\ComponentController::class, 'destroy'])->name('component.destroy');
    Route::delete('bus/delete', [App\Http\Controllers\KelasBusController::class, 'destroy'])->name('bus.destroy');
});
Route::resource('order', App\Http\Controllers\OrderTiketController::class)->except('destroy');

resources/views/komponen/create.blade.php
@extends('base')
@section('title','Komponen')
@section('komponen','active bg-warning')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Komponen</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('component.index')}}">Komponen</a></li>
                        <li class="breadcrumb-item active">Tambah</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            @if($errors->any())
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    @foreach($errors->all() as $message)
                    <p class="m-0">{{"$message"}}</p>
                    @endforeach
                </div>
            @endif
            <div class="card card-primary">
                <!-- form start -->
                <form action="{{route('component.store')}}" method="post">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label>Kode Komponen<span class="text-danger">*</span></label>
                            <input type="text" name="kode_komponen" value="{{old('kode_komponen')}}" class="form-control" placeholder="...">
                        </div>
                        <div class="form-group">
                            <label>Nama Komponen<span class="text-danger">*</span></label>
                            <input type="text" name="nama_komponen" value="{{old('nama_komponen')}}" class="form-control" placeholder="...">
                        </div>
                        <div class="form-group">
                            <label>Value Komponen<span class="text-danger">*</span></label>
                            <input type="text" name="value_komponen" value="{{old('value_komponen')}}" class="form-control" placeholder="...">
                        </div>
                        <div class="form-group">
                            <label>Grup Komponen<span class="text-danger">*</span></label>
                            <input type="text" list="grup_komponen" class="form-control" name="grup_komponen" autocomplete="off" placeholder="...">
                            <datalist id="grup_komponen">
                                @foreach ($komponen as $data)
                                    <option>{{$data->code_group }}</option>
                                @endforeach
                            </datalist>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Tambah</button>
                    </div>
                </form>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection
@push('js')
<!-- @include('component/validation') -->
@include('component/select2')
@endpush

resources/views/komponen/edit.blade.php
@extends('base')
@section('title','Komponen')
@section('komponen','active bg-warning')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Komponen</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('component.index')}}">Komponen</a></li>
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            @if($errors->any())
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    @foreach($errors->all() as $message)
                    <p class="m-0">{{"$message"}}</p>
                    @endforeach
                </div>
            @endif
            <div class="card card-primary">
                <!-- form start -->
                <form action="{{route('component.update',$data->com_cd)}}" method="post">
                    @csrf
                    @method('PUT')
                    <div class="card-body">
                        <div class="form-group">
                            <label>Kode Komponen<span class="text-danger">*</span></label>
                            <input type="text" name="kode_komponen" value="{{$data->com_cd}}" class="form-control" readonly placeholder="...">
                        </div>
                        <div class="form-group">
                            <label>Nama Komponen<span class="text-danger">*</span></label>
                            <input type="text" name="nama_komponen" value="{{$data->code_nm}}" class="form-control" placeholder="...">
                        </div>
                        <div class="form-group">
                            <label>Value Komponen<span class="text-danger">*</span></label>
                            <input type="text" name="value_komponen" value="{{$data->code_value}}" class="form-control" placeholder="...">
                        </div>
                        <div class="form-group">
                            <label>Grup Komponen<span class="text-danger">*</span></label>
                            <input type="text" list="grup_komponen" value="{{$data->code_group}}" class="form-control" name="grup_komponen" autocomplete="off" placeholder="...">
                            <datalist id="grup_komponen">
                                @foreach ($komponen as $data)
                                    <option>{{$data->code_group }}</option>
                                @endforeach
                            </datalist>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection
@push('js')
<!-- @include('component/validation') -->
@include('component/select2')
@endpush

resources/views/komponen/index.blade.php
@extends('base')
@section('title','Komponen')
@section('komponen','active bg-warning')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Komponen</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('component.index')}}">Komponen</a></li>
                        <li class="breadcrumb-item active">Data</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            @if (session('message'))
            <div class="alert alert-{{session('message')['color']}} alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{session('message')['response']}}
            </div>
            @endif
            <div class="card">
                <div class="card-header">
                    <a href="{{route('component.create')}}" class="btn btn-primary float-right">Tambah Data</a>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table class="datatable table table-bordered table-hover" width="100%">
                        <thead>
                        <tr>
                            <th style="width: 1px">#</th>
                            <th>Kode Komponen</th>
                            <th>Nama Komponen</th>
                            <th>Grup Komponen</th>
                            <th>Value Komponen</th>
                            <th style="width: 1px"></th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <div class="modal fade" id="modal-delete">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Peringatan!</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Apakah anda yakin akan menghapus data ini?</p>
                </div>
                <form action="{{route('component.destroy')}}" method="POST">
                    @csrf
                    @method('delete')
                    <div class="modal-footer justify-content-between">
                        <input type="hidden" name="id">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                        <button type="submit" class="btn btn-danger">Hapus</button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
@endsection
@push('js')
@include('component/datatable')
@include('component/tooltip')
<script>
    $(document).on("click", ".btn-delete", function () {
        var id = $(this).data('id');
        $("[name=id]").val(id);
    });
</script>
@endpush