routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('index');

Auth::routes([
    'register' => false, // remove this class to activate register route
    'reset' => false, // remove this class to activate password reset ro+ute
    'confirm' => false, // remove this class to activate password confirmation route
    'verify' => false // remove this class to activate email verification route
]);
Route::group(['middleware' => 'auth'], function () {
    Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])->name('dashboard');
    Route::get('gambar/{id}', [App\Http\Controllers\KelasBusController::class, 'listGambar'])->name('bus.gambar');
    Route::resource('component', App\Http\Controllers\ComponentController::class)->except('destroy');
    Route::resource('bus', App\Http\Controllers\KelasBusController::class)->except('destroy');
    Route::delete('component/delete', [App\Http\Controllers\ComponentController::class, 'destroy'])->name('component.destroy');
    Route::delete('bus/delete', [App\Http\Controllers\KelasBusController::class, 'destroy'])->name('bus.destroy');
});
Route::resource('order', App\Http\Controllers\OrderTiketController::class)->except('destroy');

resources/views/bus/create.blade.php
@extends('base')
@section('title','Bus')
@section('bus','active bg-warning')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Bus</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('bus.index')}}">Bus</a></li>
                        <li class="breadcrumb-item active">Tambah</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            @if($errors->any())
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    @foreach($errors->all() as $message)
                    <p class="m-0">{{"$message"}}</p>
                    @endforeach
                </div>
            @endif
            <div class="card card-primary">
                <!-- form start -->
                <form action="{{route('bus.store')}}" method="post">
                    @csrf
                    <div class="card-body">
                        <div class="form-group">
                            <label>Kelas Bus<span class="text-danger">*</span></label>
                            <input type="text" name="kelas_bus" value="{{old('kelas_bus')}}" class="form-control" placeholder="...">
                        </div>
                        <div class="form-group">
                            <label>Harga<span class="text-danger">*</span></label>
                            <input type="text" name="harga" value="{{old('harga')}}" class="form-control" placeholder="...">
                        </div>
                        <div class="form-group">
                            <label>Gambar<span class="text-danger">*</span><button type="button" class="btn btn-info" id="tbh-gambar">+</button></label>
                            <input type="file" name="gambar[]" class="form-control" placeholder="...">
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Tambah</button>
                    </div>
                </form>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection
@push('js')
<!-- @include('component/validation') -->
@include('component/select2')
<script>
    $("#tbh-gambar").click(function(){
        let gambar = "<input type='file' name='gambar[]' class='form-control' placeholder='...'>"
        $("#gambar").append(gambar);
    });
</script>
@endpush

resources/views/bus/edit.blade.php
@extends('base')
@section('title','Bus')
@section('bus','active bg-warning')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Bus</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('bus.index')}}">Bus</a></li>
                        <li class="breadcrumb-item active">Ubah</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            @if($errors->any())
                <div class="alert alert-danger alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    @foreach($errors->all() as $message)
                    <p class="m-0">{{"$message"}}</p>
                    @endforeach
                </div>
            @endif
            <div class="card card-primary">
                <!-- form start -->
                <form action="{{route('bus.update',$data->id)}}" enctype="multipart/form-data" method="post">
                    @csrf
                    @method('PUT')
                    <div class="card-body">
                        <div class="form-group">
                            <label>Kelas Bus<span class="text-danger">*</span></label>
                            <input type="text" name="kelas_bus" value="{{$data->kelas}}" class="form-control" placeholder="...">
                        </div>
                        <div class="form-group">
                            <label>Harga<span class="text-danger">*</span></label>
                            <input type="text" name="harga" value="{{$data->harga}}" class="form-control" placeholder="...">
                        </div>
                        <div class="form-group" id="gambar">
                            <label>Gambar<span class="text-danger">*</span><button type="button" class="btn btn-info" id="tbh-gambar">+</button></label>
                            <input type="file" name="gambar[]" class="form-control" placeholder="...">
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Tambah</button>
                    </div>
                </form>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection
@push('js')
<!-- @include('component/validation') -->
@include('component/select2')
<script>
    $("#tbh-gambar").click(function(){
        let gambar = "<input type='file' name='gambar[]' class='form-control' placeholder='...'>"
        $("#gambar").append(gambar);
    });
</script>
@endpush

resources/views/bus/index.blade.php
@extends('base')
@section('title','Bus')
@section('bus','active bg-warning')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Bus</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('bus.index')}}">Bus</a></li>
                        <li class="breadcrumb-item active">Data</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            @if (session('message'))
            <div class="alert alert-{{session('message')['color']}} alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{session('message')['response']}}
            </div>
            @endif
            <div class="card">
                <div class="card-header">
                    <a href="{{route('bus.create')}}" class="btn btn-primary float-right">Tambah Data</a>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table class="datatable table table-bordered table-hover" width="100%">
                        <thead>
                        <tr>
                            <th style="width: 1px">#</th>
                            <th>Kelas Bus</th>
                            <th>Harga</th>
                            <th>Gambar</th>
                            <th style="width: 1px"></th>
                        </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <div class="modal fade" id="modal-delete">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Peringatan!</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Apakah anda yakin akan menghapus data ini?</p>
                </div>
                <form action="{{route('bus.destroy')}}" method="POST">
                    @csrf
                    @method('delete')
                    <div class="modal-footer justify-content-between">
                        <input type="hidden" name="id">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Tutup</button>
                        <button type="submit" class="btn btn-danger">Hapus</button>
                    </div>
                </form>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    <div class="modal fade" id="modal-gambar">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                <div id="carouselExample" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        
                    </div>
                    <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExample" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                    </div>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
    <img src="" alt="">
@endsection
@push('js')
@include('component/datatable')
@include('component/tooltip')
<script>
    $(document).on("click", ".btn-delete", function () {
        var id = $(this).data('id');
        $("[name=id]").val(id);
    });
    $(document).on("click", ".lihat-gambar", function () {
        let id = $(this).data('id');
        $.ajax({
            url: "{{route('bus.gambar', ['id' => 'id'])}}".replace('id', id),
            type: 'GET',
            success: function(res){
                let img = '';
                $.each( res, function( key, value ) {
                    let active;
                    if (key == 0) {
                        active = 'active';
                    }
                    img += "<div class='carousel-item "+active+"'>"+
                        "<img class='d-block w-100' src='{{asset('storage/gambar-bus/namafile')}}'>".replace('namafile',value.gambar_bus)+
                        "</div>"
                });
                $('#modal-gambar .modal-body .carousel-inner').empty();
                $('#modal-gambar .modal-body .carousel-inner').html(img);
            }
        })
        $("#modal-gambar").modal({show:true});
    });
</script>
@endpush